- name: bug
  color: "d73a4a"
  description: Something isn't working

- name: enhancement
  color: "a2eeef"
  description: New feature or improvement

- name: documentation
  color: "0075ca"
  description: Documentation improvements

- name: question
  color: "d876e3"
  description: Further information is requested

- name: duplicate
  color: "cfd3d7"
  description: This issue or pull request already exists

- name: invalid
  color: "e4e669"
  description: This doesn't appear to be valid

- name: wontfix
  color: "ffffff"
  description: This will not be worked on

- name: good first issue
  color: "7057ff"
  description: Good for first-time contributors

- name: help wanted
  color: "008672"
  description: Extra attention is needed

- name: dependencies
  color: "0366d6"
  description: Dependency updates

- name: security
  color: "b60205"
  description: Security-related issue

- name: ci
  color: "1d76db"
  description: Continuous Integration

- name: github-actions
  color: "2088FF"
  description: GitHub Actions related

- name: performance
  color: "fbca04"
  description: Performance improvement

- name: refactor
  color: "5319e7"
  description: Code refactoring